name: test cprnc
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Installs
      run: |
        set -x
        sudo apt-get update
        sudo apt-get install netcdf-bin gfortran libnetcdff-dev
    - name: cmake build
      shell: bash
      run: |
        export FC=gfortran
        mkdir build
        cd build
        cmake -Wno-dev \
              -DNetCDF_Fortran_LIBRARY=/usr/lib/x86_64-linux-gnu/libnetcdff.a \
              -DNetCDF_Fortran_INCLUDE_DIR=/usr/include \
              -DNetCDF_C_LIBRARY=/usr/lib/x86_64-linux-gnu/libnetcdf.a \
              -DNetCDF_C_INCLUDE_DIR=/usr/include \
              -DCMAKE_Fortran_FLAGS="-Wall" \
              ../
        make VERBOSE=1
        make test
