name: test cprnc
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses" actions/checkout@v3
    - name: Installs
      run: |
        set -x
        sudo apt-get update
        sudo apt-get install netcdf-bin gfortran libnetcdff-dev
    - name: cmake build
      shell: bash
      run: |
        mkdir build
        cd build
        cmake -Wno-dev ../
        make VERBOSE=1
